version: "3.6"

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - "DEFAULT_MODEL=default"
      - "API_HOST=http://localhost:8000"
      - "NEXT_PUBLIC_API_TIMEOUT=600000"
